color0 #2c3021
color1 #fd4663
color2 #bdd775
color3 #81c76b
color4 #70c285
color5 #cedea1
color6 #b0dca3
color7 #f2f3f2
color8 #686e5a
color9 #fd4663
color10 #bdd775
color11 #81c76b
color12 #70c285
color13 #cedea1
color14 #b0dca3
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #21231a
background            #21231a
foreground            #f2f3f2
selection_foreground  #b4b6af
selection_background  #2c3021
active_border_color   #bdd775
inactive_border_color #2c3021
url_color             #bdd775

active_tab_foreground   #20221b
active_tab_background   #bdd775
inactive_tab_foreground #b4b6af
inactive_tab_background #2c3021
cursor_trail_color      #b4b6af
